/**
 * @file eos_config_defaults.h
 * @brief Kernel default configuration values
 *
 * DO NOT EDIT this file directly.
 * Use menuconfig (scripts/kconfig.py menuconfig) for interactive config
 * or create eos_platform_config.h for manual overrides.
 *
 * Each option checks CONFIG_<NAME> first (from generated eos_config_gen.h),
 * then manual override, and falls back to the kernel default.
 */

#ifndef EOS_CONFIG_DEFAULTS_H
#define EOS_CONFIG_DEFAULTS_H

/* Product identity -------------------------------------------*/

#ifdef CONFIG_ELENIX_WATCH_MARKETING_NAME
#define ELENIX_WATCH_MARKETING_NAME CONFIG_ELENIX_WATCH_MARKETING_NAME
#elif !defined(ELENIX_WATCH_MARKETING_NAME)
#define ELENIX_WATCH_MARKETING_NAME "Elenix Watch"
#endif

#ifdef CONFIG_ELENIX_WATCH_MODEL_NUMBER
#define ELENIX_WATCH_MODEL_NUMBER CONFIG_ELENIX_WATCH_MODEL_NUMBER
#elif !defined(ELENIX_WATCH_MODEL_NUMBER)
#define ELENIX_WATCH_MODEL_NUMBER "S2508(0)"
#endif

/* Build / compilation mode -----------------------------------*/

#if defined(CONFIG_EOS_COMPILE_MODE_DEBUG) && CONFIG_EOS_COMPILE_MODE_DEBUG
#define EOS_COMPILE_MODE DEBUG
#elif defined(CONFIG_EOS_COMPILE_MODE_RELEASE) && CONFIG_EOS_COMPILE_MODE_RELEASE
#define EOS_COMPILE_MODE RELEASE
#elif !defined(EOS_COMPILE_MODE)
#define EOS_COMPILE_MODE DEBUG
#endif

/* Feature switches -------------------------------------------*/

#ifdef CONFIG_EOS_ICON_STR_BUILD_IN
#define EOS_ICON_STR_BUILD_IN CONFIG_EOS_ICON_STR_BUILD_IN
#elif !defined(EOS_ICON_STR_BUILD_IN)
#define EOS_ICON_STR_BUILD_IN 0
#endif

#ifdef CONFIG_EOS_USE_VIRTUAL_DISPLAY
#define EOS_USE_VIRTUAL_DISPLAY CONFIG_EOS_USE_VIRTUAL_DISPLAY
#elif !defined(EOS_USE_VIRTUAL_DISPLAY)
#define EOS_USE_VIRTUAL_DISPLAY 1
#endif

/* Memory -----------------------------------------------------*/

#if defined(CONFIG_EOS_MEM_PROVIDER_STDLIB_CLIB) && CONFIG_EOS_MEM_PROVIDER_STDLIB_CLIB
#define EOS_MEM_ALLOC_PROVIDER EOS_MEM_PROVIDER_STDLIB_CLIB
#elif defined(CONFIG_EOS_MEM_PROVIDER_AUTO) && CONFIG_EOS_MEM_PROVIDER_AUTO
#define EOS_MEM_ALLOC_PROVIDER EOS_MEM_PROVIDER_AUTO
#elif defined(CONFIG_EOS_MEM_PROVIDER_CUSTOM) && CONFIG_EOS_MEM_PROVIDER_CUSTOM
#define EOS_MEM_ALLOC_PROVIDER EOS_MEM_PROVIDER_CUSTOM
#elif !defined(EOS_MEM_ALLOC_PROVIDER)
#define EOS_MEM_ALLOC_PROVIDER EOS_MEM_PROVIDER_STDLIB_CLIB
#endif

#if EOS_MEM_ALLOC_PROVIDER == EOS_MEM_PROVIDER_AUTO
    #ifdef CONFIG_EOS_MEM_POOL_ALLOC_THRESHOLD
    #define EOS_MEM_POOL_ALLOC_THRESHOLD CONFIG_EOS_MEM_POOL_ALLOC_THRESHOLD
    #elif !defined(EOS_MEM_POOL_ALLOC_THRESHOLD)
    #define EOS_MEM_POOL_ALLOC_THRESHOLD (32 * 1024)
    #endif

    #define EOS_MEM_PROVIDER_AUTO_INCLUDE  "mem_mgr.h"
    #define EOS_MEM_ALLOC_FAST             malloc
    #define EOS_MEM_ALLOC_LARGE            mem_mgr_alloc
    #define EOS_MEM_FREE_FAST              free
    #define EOS_MEM_FREE_LARGE             mem_mgr_free
    #define EOS_MEM_REALLOC_FAST           realloc
    #define EOS_MEM_REALLOC_LARGE          mem_mgr_realloc
    #define EOS_MEM_CALLOC_FAST            calloc
    #define EOS_MEM_CALLOC_LARGE           mem_mgr_calloc
#elif !defined(EOS_MEM_POOL_ALLOC_THRESHOLD)
#define EOS_MEM_POOL_ALLOC_THRESHOLD 0
#endif

#ifdef CONFIG_EOS_OVERRIDE_LVGL_STDLIB_MALLOC_ENABLE
#define EOS_OVERRIDE_LVGL_STDLIB_MALLOC_ENABLE CONFIG_EOS_OVERRIDE_LVGL_STDLIB_MALLOC_ENABLE
#elif !defined(EOS_OVERRIDE_LVGL_STDLIB_MALLOC_ENABLE)
#define EOS_OVERRIDE_LVGL_STDLIB_MALLOC_ENABLE \
    (LV_USE_STDLIB_MALLOC == LV_STDLIB_CUSTOM)
#endif

#ifdef CONFIG_EOS_MEM_TRACK_ENABLE
#define EOS_MEM_TRACK_ENABLE CONFIG_EOS_MEM_TRACK_ENABLE
#elif !defined(EOS_MEM_TRACK_ENABLE)
#define EOS_MEM_TRACK_ENABLE 1
#endif

/* Image cache -------------------------------------------------*/

#ifdef CONFIG_EOS_CACHE_ENABLE
#define EOS_CACHE_ENABLE CONFIG_EOS_CACHE_ENABLE
#elif !defined(EOS_CACHE_ENABLE)
#define EOS_CACHE_ENABLE 1
#endif

#ifdef CONFIG_EOS_CACHE_SIZE
#define EOS_CACHE_SIZE CONFIG_EOS_CACHE_SIZE
#elif defined(IMAGE_CACHE_IN_PSRAM_SIZE) && (IMAGE_CACHE_IN_PSRAM_SIZE > 0)
#define EOS_CACHE_SIZE ((uint32_t)(IMAGE_CACHE_IN_PSRAM_SIZE))
#elif defined(IMAGE_CACHE_IN_SRAM_SIZE) && (IMAGE_CACHE_IN_SRAM_SIZE > 0)
#define EOS_CACHE_SIZE ((uint32_t)(IMAGE_CACHE_IN_SRAM_SIZE))
#elif !defined(EOS_CACHE_SIZE)
#define EOS_CACHE_SIZE (128U * 1024U)
#endif

#ifdef CONFIG_EOS_CACHE_HEADER_COUNT
#define EOS_CACHE_HEADER_COUNT CONFIG_EOS_CACHE_HEADER_COUNT
#elif !defined(EOS_CACHE_HEADER_COUNT)
#define EOS_CACHE_HEADER_COUNT 16U
#endif

#ifdef CONFIG_EOS_CACHE_USE_DEDICATED_MEM
#define EOS_CACHE_USE_DEDICATED_MEM CONFIG_EOS_CACHE_USE_DEDICATED_MEM
#elif defined(BSP_USING_PSRAM) || defined(IMAGE_CACHE_IN_PSRAM_SIZE)
#define EOS_CACHE_USE_DEDICATED_MEM 1
#elif !defined(EOS_CACHE_USE_DEDICATED_MEM)
#define EOS_CACHE_USE_DEDICATED_MEM 0
#endif

/* RTOS --------------------------------------------------------*/

#if defined(CONFIG_EOS_RTOS_BARE_METAL) && CONFIG_EOS_RTOS_BARE_METAL
#define EOS_RTOS_TYPE EOS_RTOS_BARE_METAL
#elif defined(CONFIG_EOS_RTOS_FREERTOS) && CONFIG_EOS_RTOS_FREERTOS
#define EOS_RTOS_TYPE EOS_RTOS_FREERTOS
#elif defined(CONFIG_EOS_RTOS_RTTHREAD) && CONFIG_EOS_RTOS_RTTHREAD
#define EOS_RTOS_TYPE EOS_RTOS_RTTHREAD
#elif defined(CONFIG_EOS_RTOS_POSIX) && CONFIG_EOS_RTOS_POSIX
#define EOS_RTOS_TYPE EOS_RTOS_POSIX
#elif defined(CONFIG_EOS_RTOS_CUSTOM) && CONFIG_EOS_RTOS_CUSTOM
#define EOS_RTOS_TYPE EOS_RTOS_CUSTOM
#elif !defined(EOS_RTOS_TYPE)
#define EOS_RTOS_TYPE EOS_RTOS_BARE_METAL
#endif

/* Font --------------------------------------------------------*/

#if defined(CONFIG_EOS_FONT_C_MULTI) && CONFIG_EOS_FONT_C_MULTI
#define EOS_FONT_TYPE EOS_FONT_C_MULTI
#elif defined(CONFIG_EOS_FONT_TTF) && CONFIG_EOS_FONT_TTF
#define EOS_FONT_TYPE EOS_FONT_TTF
#elif !defined(EOS_FONT_TYPE)
#define EOS_FONT_TYPE EOS_FONT_TTF
#endif

#ifdef CONFIG_EOS_FONT_CFG_LARGE_SIZE
#define EOS_FONT_CFG_LARGE_SIZE CONFIG_EOS_FONT_CFG_LARGE_SIZE
#elif !defined(EOS_FONT_CFG_LARGE_SIZE)
#define EOS_FONT_CFG_LARGE_SIZE 30
#endif

#ifdef CONFIG_EOS_FONT_CFG_MEDIUM_SIZE
#define EOS_FONT_CFG_MEDIUM_SIZE CONFIG_EOS_FONT_CFG_MEDIUM_SIZE
#elif !defined(EOS_FONT_CFG_MEDIUM_SIZE)
#define EOS_FONT_CFG_MEDIUM_SIZE (EOS_FONT_CFG_LARGE_SIZE - 4)
#endif

#ifdef CONFIG_EOS_FONT_CFG_SMALL_SIZE
#define EOS_FONT_CFG_SMALL_SIZE CONFIG_EOS_FONT_CFG_SMALL_SIZE
#elif !defined(EOS_FONT_CFG_SMALL_SIZE)
#define EOS_FONT_CFG_SMALL_SIZE (EOS_FONT_CFG_MEDIUM_SIZE - 4)
#endif

#if EOS_FONT_TYPE == EOS_FONT_C_MULTI

    #ifndef EOS_ENABLE_CHINESE_FONT
    #define EOS_ENABLE_CHINESE_FONT 1
    #endif

    #if EOS_ENABLE_CHINESE_FONT
        #define EOS_FONT_LARGE_NAME  source_han_sans_30
        #define EOS_FONT_MEDIUM_NAME source_han_sans_26
        #define EOS_FONT_SMALL_NAME  source_han_sans_22
    #else
        #define EOS_FONT_LARGE_NAME  lv_font_montserrat_30
        #define EOS_FONT_MEDIUM_NAME lv_font_montserrat_30
        #define EOS_FONT_SMALL_NAME  lv_font_montserrat_30
    #endif

#elif EOS_FONT_TYPE == EOS_FONT_TTF

    #if defined(CONFIG_EOS_FONT_TTF_DATA) && CONFIG_EOS_FONT_TTF_DATA
    #define EOS_FONT_TTF_TYPE EOS_FONT_TTF_DATA
    #elif defined(CONFIG_EOS_FONT_TTF_FILE) && CONFIG_EOS_FONT_TTF_FILE
    #define EOS_FONT_TTF_TYPE EOS_FONT_TTF_FILE
    #elif !defined(EOS_FONT_TTF_TYPE)
    #define EOS_FONT_TTF_TYPE EOS_FONT_TTF_FILE
    #endif

    #if EOS_FONT_TTF_TYPE == EOS_FONT_TTF_DATA
        #define EOS_FONT_TTF_DATA_NAME SourceHanSansSC_12M
        #define EOS_FONT_TTF_DATA_SIZE SourceHanSansSC_12M_size
    #elif EOS_FONT_TTF_TYPE == EOS_FONT_TTF_FILE
        #if !defined(EOS_FONT_TTF_FILE_PATH)
        #ifdef CONFIG_EOS_FONT_TTF_FILE_PATH
        #define EOS_FONT_TTF_FILE_PATH EOS_SYS_RES_FONT_DIR CONFIG_EOS_FONT_TTF_FILE_PATH
        #else
        #define EOS_FONT_TTF_FILE_PATH EOS_SYS_RES_FONT_DIR "font.ttf"
        #endif
        #endif
    #endif

    #ifdef CONFIG_EOS_FONT_TTF_ENABLE_EXTENDED
    #define EOS_FONT_TTF_ENABLE_EXTENDED CONFIG_EOS_FONT_TTF_ENABLE_EXTENDED
    #elif !defined(EOS_FONT_TTF_ENABLE_EXTENDED)
    #define EOS_FONT_TTF_ENABLE_EXTENDED 0
    #endif

    #if EOS_FONT_TTF_ENABLE_EXTENDED
        #ifdef CONFIG_EOS_FONT_TTF_KERNING
        #define EOS_FONT_TTF_KERNING CONFIG_EOS_FONT_TTF_KERNING
        #elif !defined(EOS_FONT_TTF_KERNING)
        #define EOS_FONT_TTF_KERNING 0
        #endif
        #ifdef CONFIG_EOS_FONT_TTF_CACHE_SIZE
        #define EOS_FONT_TTF_CACHE_SIZE CONFIG_EOS_FONT_TTF_CACHE_SIZE
        #elif !defined(EOS_FONT_TTF_CACHE_SIZE)
        #define EOS_FONT_TTF_CACHE_SIZE 256
        #endif
    #endif

#endif /* EOS_FONT_TYPE */

/* Display -----------------------------------------------------*/

#ifdef CONFIG_EOS_DISPLAY_WIDTH
#define EOS_DISPLAY_WIDTH CONFIG_EOS_DISPLAY_WIDTH
#elif !defined(EOS_DISPLAY_WIDTH)
#define EOS_DISPLAY_WIDTH 390
#endif

#ifdef CONFIG_EOS_DISPLAY_HEIGHT
#define EOS_DISPLAY_HEIGHT CONFIG_EOS_DISPLAY_HEIGHT
#elif !defined(EOS_DISPLAY_HEIGHT)
#define EOS_DISPLAY_HEIGHT 450
#endif

#ifdef CONFIG_EOS_DISPLAY_RADIUS
#define EOS_DISPLAY_RADIUS CONFIG_EOS_DISPLAY_RADIUS
#elif !defined(EOS_DISPLAY_RADIUS)
#define EOS_DISPLAY_RADIUS 80
#endif

#ifdef CONFIG_EOS_DISPLAY_BRIGHTNESS_MIN
#define EOS_DISPLAY_BRIGHTNESS_MIN CONFIG_EOS_DISPLAY_BRIGHTNESS_MIN
#elif !defined(EOS_DISPLAY_BRIGHTNESS_MIN)
#define EOS_DISPLAY_BRIGHTNESS_MIN 5
#endif

#ifdef CONFIG_EOS_DISPLAY_BRIGHTNESS_MAX
#define EOS_DISPLAY_BRIGHTNESS_MAX CONFIG_EOS_DISPLAY_BRIGHTNESS_MAX
#elif !defined(EOS_DISPLAY_BRIGHTNESS_MAX)
#define EOS_DISPLAY_BRIGHTNESS_MAX 100
#endif

/* File system -------------------------------------------------*/

#if !defined(EOS_SYS_ROOT_DIR)
#ifdef CONFIG_EOS_SYS_ROOT_DIR
#define EOS_SYS_ROOT_DIR CONFIG_EOS_SYS_ROOT_DIR
#else
#define EOS_SYS_ROOT_DIR "/"
#endif
#endif

#if defined(CONFIG_EOS_FS_POSIX) && CONFIG_EOS_FS_POSIX
#define EOS_FS_TYPE EOS_FS_POSIX
#elif defined(CONFIG_EOS_FS_FATFS) && CONFIG_EOS_FS_FATFS
#define EOS_FS_TYPE EOS_FS_FATFS
#elif defined(CONFIG_EOS_FS_LITTLEFS) && CONFIG_EOS_FS_LITTLEFS
#define EOS_FS_TYPE EOS_FS_LITTLEFS
#elif defined(CONFIG_EOS_FS_RTTHREAD) && CONFIG_EOS_FS_RTTHREAD
#define EOS_FS_TYPE EOS_FS_RTTHREAD
#elif defined(CONFIG_EOS_FS_CUSTOM) && CONFIG_EOS_FS_CUSTOM
#define EOS_FS_TYPE EOS_FS_CUSTOM
#elif !defined(EOS_FS_TYPE)
#define EOS_FS_TYPE EOS_FS_POSIX
#endif

#if EOS_FS_TYPE == EOS_FS_CUSTOM
    #define EOS_FS_FILE_TYPE  void *
    #define EOS_FS_DIR_TYPE   void *
    #define EOS_FILE_INVALID  NULL
    #define EOS_DIR_INVALID   NULL
#endif

#ifdef CONFIG_EOS_FS_PATH_MAX
#define EOS_FS_PATH_MAX CONFIG_EOS_FS_PATH_MAX
#elif !defined(EOS_FS_PATH_MAX)
#define EOS_FS_PATH_MAX 256
#endif

#ifdef CONFIG_EOS_LVGL_FS_LETTER
#define EOS_LVGL_FS_LETTER CONFIG_EOS_LVGL_FS_LETTER
#elif !defined(EOS_LVGL_FS_LETTER)
#define EOS_LVGL_FS_LETTER 'Z'
#endif

#ifdef CONFIG_EOS_DFW_ENABLE
#define EOS_DFW_ENABLE CONFIG_EOS_DFW_ENABLE
#elif !defined(EOS_DFW_ENABLE)
#define EOS_DFW_ENABLE 0
#endif

/* Language ----------------------------------------------------*/

#if defined(CONFIG_EOS_LANG_ZH) && CONFIG_EOS_LANG_ZH
#define EOS_CONFIG_DEFAULT_LANGUAGE EOS_LANG_ZH
#elif defined(CONFIG_EOS_LANG_EN) && CONFIG_EOS_LANG_EN
#define EOS_CONFIG_DEFAULT_LANGUAGE EOS_LANG_EN
#elif !defined(EOS_CONFIG_DEFAULT_LANGUAGE)
#define EOS_CONFIG_DEFAULT_LANGUAGE 0
#endif

/* Miscellaneous -----------------------------------------------*/

#ifdef CONFIG_EOS_ENABLE_TEST_APP
#define EOS_ENABLE_TEST_APP CONFIG_EOS_ENABLE_TEST_APP
#elif !defined(EOS_ENABLE_TEST_APP)
#define EOS_ENABLE_TEST_APP 1
#endif

/* Logging -----------------------------------------------------*/

#ifdef CONFIG_EOS_USE_ASSERT
#define EOS_USE_ASSERT CONFIG_EOS_USE_ASSERT
#elif !defined(EOS_USE_ASSERT)
#define EOS_USE_ASSERT 1
#endif

#ifndef EOS_ASSERT_HANDLER
#define EOS_ASSERT_HANDLER __builtin_trap();
#endif

#ifdef CONFIG_EOS_LOG_USE_COLOR
#define EOS_LOG_USE_COLOR CONFIG_EOS_LOG_USE_COLOR
#elif !defined(EOS_LOG_USE_COLOR)
#define EOS_LOG_USE_COLOR 0
#endif

#ifdef CONFIG_EOS_LOG_MAX_LISTENERS
#define EOS_LOG_MAX_LISTENERS CONFIG_EOS_LOG_MAX_LISTENERS
#elif !defined(EOS_LOG_MAX_LISTENERS)
#define EOS_LOG_MAX_LISTENERS 8
#endif

#ifdef CONFIG_EOS_LOG_ENABLE_STD
#define EOS_LOG_ENABLE_STD CONFIG_EOS_LOG_ENABLE_STD
#elif !defined(EOS_LOG_ENABLE_STD)
#define EOS_LOG_ENABLE_STD 1
#endif

#endif /* EOS_CONFIG_DEFAULTS_H */
