/**
 * @file eos_config_defaults.h
 * @brief Kernel default configuration values
 *
 * This file provides FALLBACK defaults for every configurable option.
 * It uses the #ifndef pattern – if a value has already been set by
 * any platform layer (generated header, -D flag, eos_platform_config.h),
 * the default is skipped.
 *
 * This header knows NOTHING about CONFIG_ prefixes or any specific
 * Kconfig system.  It is purely a fallback-defaults provider.
 *
 * Override priority (highest to lowest):
 *   1. Compiler -D flags (e.g. CPPDEFINES)
 *   2. eos_platform_config.h       (manual, project-specific)
 *   3. eos_config_gen.h            (generated by a Kconfig system)
 *   4. This file                   (kernel fallback defaults)
 */

#ifndef EOS_CONFIG_DEFAULTS_H
#define EOS_CONFIG_DEFAULTS_H

/* Product identity -------------------------------------------*/

#ifndef ELENIX_WATCH_MARKETING_NAME
#define ELENIX_WATCH_MARKETING_NAME "Elenix Watch"
#endif

#ifndef ELENIX_WATCH_MODEL_NUMBER
#define ELENIX_WATCH_MODEL_NUMBER "S2508(0)"
#endif

/* Build / compilation mode -----------------------------------*/

#ifndef EOS_COMPILE_MODE
#define EOS_COMPILE_MODE EOS_DEBUG
#endif

/* Feature switches -------------------------------------------*/

#ifndef EOS_ICON_STR_BUILD_IN
#define EOS_ICON_STR_BUILD_IN 0
#endif

#ifndef EOS_CONFIG_ANIM_SNAPSHOT_ENABLED
#define EOS_CONFIG_ANIM_SNAPSHOT_ENABLED 1
#endif

#ifndef EOS_USE_VIRTUAL_DISPLAY
#define EOS_USE_VIRTUAL_DISPLAY 1
#endif

/* Memory -----------------------------------------------------*/

#ifndef EOS_MEM_MAX_REGIONS
#define EOS_MEM_MAX_REGIONS 16U
#endif

#ifndef EOS_MEM_ALLOC_PROVIDER
#define EOS_MEM_ALLOC_PROVIDER EOS_MEM_PROVIDER_STDLIB_CLIB
#endif

#ifndef EOS_MEM_POOL_ALLOC_THRESHOLD
#if EOS_MEM_ALLOC_PROVIDER == EOS_MEM_PROVIDER_AUTO
#define EOS_MEM_POOL_ALLOC_THRESHOLD (32 * 1024)
#else
#define EOS_MEM_POOL_ALLOC_THRESHOLD 0
#endif
#endif

#if EOS_MEM_ALLOC_PROVIDER == EOS_MEM_PROVIDER_AUTO
#define EOS_MEM_PROVIDER_AUTO_INCLUDE "mem_mgr.h"
#define EOS_MEM_ALLOC_FAST malloc
#define EOS_MEM_ALLOC_LARGE mem_mgr_alloc
#define EOS_MEM_FREE_FAST free
#define EOS_MEM_FREE_LARGE mem_mgr_free
#define EOS_MEM_REALLOC_FAST realloc
#define EOS_MEM_REALLOC_LARGE mem_mgr_realloc
#define EOS_MEM_CALLOC_FAST calloc
#define EOS_MEM_CALLOC_LARGE mem_mgr_calloc
#endif

#ifndef EOS_OVERRIDE_LVGL_STDLIB_MALLOC_ENABLE
#define EOS_OVERRIDE_LVGL_STDLIB_MALLOC_ENABLE (LV_USE_STDLIB_MALLOC == LV_STDLIB_CUSTOM)
#endif

#ifndef EOS_MEM_TRACK_ENABLE
#define EOS_MEM_TRACK_ENABLE 1
#endif

/* Kept for configuration compatibility with older ports. The current
 * tracker stores metadata in each allocation and does not have a fixed-size
 * allocation table, so this value no longer limits the number of blocks. */
#ifndef EOS_MEM_TRACK_TABLE_SIZE
#define EOS_MEM_TRACK_TABLE_SIZE 4096
#endif

/* Image cache ------------------------------------------------*/

#ifndef EOS_CACHE_ENABLE
#define EOS_CACHE_ENABLE 1
#endif

#ifndef EOS_CACHE_SIZE
#if defined(IMAGE_CACHE_IN_PSRAM_SIZE) && (IMAGE_CACHE_IN_PSRAM_SIZE > 0)
#define EOS_CACHE_SIZE ((uint32_t)(IMAGE_CACHE_IN_PSRAM_SIZE))
#elif defined(IMAGE_CACHE_IN_SRAM_SIZE) && (IMAGE_CACHE_IN_SRAM_SIZE > 0)
#define EOS_CACHE_SIZE ((uint32_t)(IMAGE_CACHE_IN_SRAM_SIZE))
#else
#define EOS_CACHE_SIZE (384U * 1024U)
#endif
#endif

#ifndef EOS_CACHE_HEADER_COUNT
#define EOS_CACHE_HEADER_COUNT 16U
#endif

#ifndef EOS_CACHE_USE_DEDICATED_MEM
#if defined(BSP_USING_PSRAM) || defined(IMAGE_CACHE_IN_PSRAM_SIZE)
#define EOS_CACHE_USE_DEDICATED_MEM 1
#else
#define EOS_CACHE_USE_DEDICATED_MEM 0
#endif
#endif

/* RTOS -------------------------------------------------------*/

#ifndef EOS_RTOS_TYPE
#define EOS_RTOS_TYPE EOS_RTOS_BARE_METAL
#endif

/* Font -------------------------------------------------------*/

#ifndef EOS_FONT_TYPE
#define EOS_FONT_TYPE EOS_FONT_TTF
#endif

#ifndef EOS_FONT_CFG_LARGE_SIZE
#define EOS_FONT_CFG_LARGE_SIZE 30
#endif

#ifndef EOS_FONT_CFG_MEDIUM_SIZE
#define EOS_FONT_CFG_MEDIUM_SIZE (EOS_FONT_CFG_LARGE_SIZE - 4)
#endif

#ifndef EOS_FONT_CFG_SMALL_SIZE
#define EOS_FONT_CFG_SMALL_SIZE (EOS_FONT_CFG_MEDIUM_SIZE - 4)
#endif

#if EOS_FONT_TYPE == EOS_FONT_C_MULTI

#ifndef EOS_ENABLE_CHINESE_FONT
#define EOS_ENABLE_CHINESE_FONT 1
#endif

#if EOS_ENABLE_CHINESE_FONT
#define EOS_FONT_LARGE_NAME source_han_sans_30
#define EOS_FONT_MEDIUM_NAME source_han_sans_26
#define EOS_FONT_SMALL_NAME source_han_sans_22
#else
#define EOS_FONT_LARGE_NAME lv_font_montserrat_30
#define EOS_FONT_MEDIUM_NAME lv_font_montserrat_30
#define EOS_FONT_SMALL_NAME lv_font_montserrat_30
#endif

#elif EOS_FONT_TYPE == EOS_FONT_TTF

#ifndef EOS_FONT_TTF_TYPE
#define EOS_FONT_TTF_TYPE EOS_FONT_TTF_FILE
#endif

#if EOS_FONT_TTF_TYPE == EOS_FONT_TTF_DATA
#define EOS_FONT_TTF_DATA_NAME SourceHanSansSC_12M
#define EOS_FONT_TTF_DATA_SIZE SourceHanSansSC_12M_size
#elif EOS_FONT_TTF_TYPE == EOS_FONT_TTF_FILE
#if !defined(EOS_FONT_TTF_FILE_PATH)
#define EOS_FONT_TTF_FILE_PATH EOS_SYS_RES_FONT_DIR "font.ttf"
#endif
#endif

#ifndef EOS_FONT_TTF_ENABLE_EXTENDED
#define EOS_FONT_TTF_ENABLE_EXTENDED 0
#endif

#ifndef EOS_FONT_TTF_FALLBACK_PTR
#ifdef EOS_FONT_TTF_FALLBACK_NAME
#define EOS_FONT_TTF_FALLBACK_PTR (&EOS_FONT_TTF_FALLBACK_NAME)
#elif defined(EOSCFG_FONT_TTF_FALLBACK_MONTSERRAT_8) && EOSCFG_FONT_TTF_FALLBACK_MONTSERRAT_8
#define EOS_FONT_TTF_FALLBACK_PTR (&lv_font_montserrat_8)
#elif defined(EOSCFG_FONT_TTF_FALLBACK_MONTSERRAT_10) && EOSCFG_FONT_TTF_FALLBACK_MONTSERRAT_10
#define EOS_FONT_TTF_FALLBACK_PTR (&lv_font_montserrat_10)
#elif defined(EOSCFG_FONT_TTF_FALLBACK_MONTSERRAT_12) && EOSCFG_FONT_TTF_FALLBACK_MONTSERRAT_12
#define EOS_FONT_TTF_FALLBACK_PTR (&lv_font_montserrat_12)
#elif defined(EOSCFG_FONT_TTF_FALLBACK_MONTSERRAT_14) && EOSCFG_FONT_TTF_FALLBACK_MONTSERRAT_14
#define EOS_FONT_TTF_FALLBACK_PTR (&lv_font_montserrat_14)
#elif defined(EOSCFG_FONT_TTF_FALLBACK_MONTSERRAT_16) && EOSCFG_FONT_TTF_FALLBACK_MONTSERRAT_16
#define EOS_FONT_TTF_FALLBACK_PTR (&lv_font_montserrat_16)
#elif defined(EOSCFG_FONT_TTF_FALLBACK_MONTSERRAT_18) && EOSCFG_FONT_TTF_FALLBACK_MONTSERRAT_18
#define EOS_FONT_TTF_FALLBACK_PTR (&lv_font_montserrat_18)
#elif defined(EOSCFG_FONT_TTF_FALLBACK_MONTSERRAT_20) && EOSCFG_FONT_TTF_FALLBACK_MONTSERRAT_20
#define EOS_FONT_TTF_FALLBACK_PTR (&lv_font_montserrat_20)
#elif defined(EOSCFG_FONT_TTF_FALLBACK_MONTSERRAT_22) && EOSCFG_FONT_TTF_FALLBACK_MONTSERRAT_22
#define EOS_FONT_TTF_FALLBACK_PTR (&lv_font_montserrat_22)
#elif defined(EOSCFG_FONT_TTF_FALLBACK_MONTSERRAT_24) && EOSCFG_FONT_TTF_FALLBACK_MONTSERRAT_24
#define EOS_FONT_TTF_FALLBACK_PTR (&lv_font_montserrat_24)
#elif defined(EOSCFG_FONT_TTF_FALLBACK_MONTSERRAT_26) && EOSCFG_FONT_TTF_FALLBACK_MONTSERRAT_26
#define EOS_FONT_TTF_FALLBACK_PTR (&lv_font_montserrat_26)
#elif defined(EOSCFG_FONT_TTF_FALLBACK_MONTSERRAT_28) && EOSCFG_FONT_TTF_FALLBACK_MONTSERRAT_28
#define EOS_FONT_TTF_FALLBACK_PTR (&lv_font_montserrat_28)
#elif defined(EOSCFG_FONT_TTF_FALLBACK_MONTSERRAT_30) && EOSCFG_FONT_TTF_FALLBACK_MONTSERRAT_30
#define EOS_FONT_TTF_FALLBACK_PTR (&lv_font_montserrat_30)
#elif defined(EOSCFG_FONT_TTF_FALLBACK_MONTSERRAT_32) && EOSCFG_FONT_TTF_FALLBACK_MONTSERRAT_32
#define EOS_FONT_TTF_FALLBACK_PTR (&lv_font_montserrat_32)
#elif defined(EOSCFG_FONT_TTF_FALLBACK_MONTSERRAT_34) && EOSCFG_FONT_TTF_FALLBACK_MONTSERRAT_34
#define EOS_FONT_TTF_FALLBACK_PTR (&lv_font_montserrat_34)
#elif defined(EOSCFG_FONT_TTF_FALLBACK_MONTSERRAT_36) && EOSCFG_FONT_TTF_FALLBACK_MONTSERRAT_36
#define EOS_FONT_TTF_FALLBACK_PTR (&lv_font_montserrat_36)
#elif defined(EOSCFG_FONT_TTF_FALLBACK_MONTSERRAT_38) && EOSCFG_FONT_TTF_FALLBACK_MONTSERRAT_38
#define EOS_FONT_TTF_FALLBACK_PTR (&lv_font_montserrat_38)
#elif defined(EOSCFG_FONT_TTF_FALLBACK_MONTSERRAT_40) && EOSCFG_FONT_TTF_FALLBACK_MONTSERRAT_40
#define EOS_FONT_TTF_FALLBACK_PTR (&lv_font_montserrat_40)
#elif defined(EOSCFG_FONT_TTF_FALLBACK_MONTSERRAT_42) && EOSCFG_FONT_TTF_FALLBACK_MONTSERRAT_42
#define EOS_FONT_TTF_FALLBACK_PTR (&lv_font_montserrat_42)
#elif defined(EOSCFG_FONT_TTF_FALLBACK_MONTSERRAT_44) && EOSCFG_FONT_TTF_FALLBACK_MONTSERRAT_44
#define EOS_FONT_TTF_FALLBACK_PTR (&lv_font_montserrat_44)
#elif defined(EOSCFG_FONT_TTF_FALLBACK_MONTSERRAT_46) && EOSCFG_FONT_TTF_FALLBACK_MONTSERRAT_46
#define EOS_FONT_TTF_FALLBACK_PTR (&lv_font_montserrat_46)
#elif defined(EOSCFG_FONT_TTF_FALLBACK_MONTSERRAT_48) && EOSCFG_FONT_TTF_FALLBACK_MONTSERRAT_48
#define EOS_FONT_TTF_FALLBACK_PTR (&lv_font_montserrat_48)
#elif defined(EOSCFG_FONT_TTF_FALLBACK_MONTSERRAT_28_COMPRESSED) && EOSCFG_FONT_TTF_FALLBACK_MONTSERRAT_28_COMPRESSED
#define EOS_FONT_TTF_FALLBACK_PTR (&lv_font_montserrat_28_compressed)
#elif defined(EOSCFG_FONT_TTF_FALLBACK_DEJAVU_16_PERSIAN_HEBREW) && EOSCFG_FONT_TTF_FALLBACK_DEJAVU_16_PERSIAN_HEBREW
#define EOS_FONT_TTF_FALLBACK_PTR (&lv_font_dejavu_16_persian_hebrew)
#elif defined(EOSCFG_FONT_TTF_FALLBACK_SOURCE_HAN_SANS_SC_14_CJK) && EOSCFG_FONT_TTF_FALLBACK_SOURCE_HAN_SANS_SC_14_CJK
#define EOS_FONT_TTF_FALLBACK_PTR (&lv_font_source_han_sans_sc_14_cjk)
#elif defined(EOSCFG_FONT_TTF_FALLBACK_SOURCE_HAN_SANS_SC_16_CJK) && EOSCFG_FONT_TTF_FALLBACK_SOURCE_HAN_SANS_SC_16_CJK
#define EOS_FONT_TTF_FALLBACK_PTR (&lv_font_source_han_sans_sc_16_cjk)
#elif defined(EOSCFG_FONT_TTF_FALLBACK_UNSCII_8) && EOSCFG_FONT_TTF_FALLBACK_UNSCII_8
#define EOS_FONT_TTF_FALLBACK_PTR (&lv_font_unscii_8)
#elif defined(EOSCFG_FONT_TTF_FALLBACK_UNSCII_16) && EOSCFG_FONT_TTF_FALLBACK_UNSCII_16
#define EOS_FONT_TTF_FALLBACK_PTR (&lv_font_unscii_16)
#elif defined(EOSCFG_FONT_TTF_FALLBACK_SIMYOU_30_CH) && EOSCFG_FONT_TTF_FALLBACK_SIMYOU_30_CH
#define EOS_FONT_TTF_FALLBACK_PTR (&lv_font_simyou_30_ch)
#elif defined(EOSCFG_FONT_TTF_FALLBACK_UBUNTU_12) && EOSCFG_FONT_TTF_FALLBACK_UBUNTU_12
#define EOS_FONT_TTF_FALLBACK_PTR (lv_font_ubuntu_12)
#elif defined(EOSCFG_FONT_TTF_FALLBACK_UBUNTU_14) && EOSCFG_FONT_TTF_FALLBACK_UBUNTU_14
#define EOS_FONT_TTF_FALLBACK_PTR (lv_font_ubuntu_14)
#elif defined(EOSCFG_FONT_TTF_FALLBACK_UBUNTU_16) && EOSCFG_FONT_TTF_FALLBACK_UBUNTU_16
#define EOS_FONT_TTF_FALLBACK_PTR (lv_font_ubuntu_16)
#elif defined(EOSCFG_FONT_TTF_FALLBACK_UBUNTU_18) && EOSCFG_FONT_TTF_FALLBACK_UBUNTU_18
#define EOS_FONT_TTF_FALLBACK_PTR (lv_font_ubuntu_18)
#elif defined(EOSCFG_FONT_TTF_FALLBACK_UBUNTU_20) && EOSCFG_FONT_TTF_FALLBACK_UBUNTU_20
#define EOS_FONT_TTF_FALLBACK_PTR (lv_font_ubuntu_20)
#elif defined(EOSCFG_FONT_TTF_FALLBACK_UBUNTU_24) && EOSCFG_FONT_TTF_FALLBACK_UBUNTU_24
#define EOS_FONT_TTF_FALLBACK_PTR (lv_font_ubuntu_24)
#elif defined(EOSCFG_FONT_TTF_FALLBACK_UBUNTU_28) && EOSCFG_FONT_TTF_FALLBACK_UBUNTU_28
#define EOS_FONT_TTF_FALLBACK_PTR (lv_font_ubuntu_28)
#elif defined(EOSCFG_FONT_TTF_FALLBACK_UBUNTU_36) && EOSCFG_FONT_TTF_FALLBACK_UBUNTU_36
#define EOS_FONT_TTF_FALLBACK_PTR (lv_font_ubuntu_36)
#elif defined(EOSCFG_FONT_TTF_FALLBACK_UBUNTU_56) && EOSCFG_FONT_TTF_FALLBACK_UBUNTU_56
#define EOS_FONT_TTF_FALLBACK_PTR (lv_font_ubuntu_56)
#elif defined(EOSCFG_FONT_TTF_FALLBACK_UBUNTU_72) && EOSCFG_FONT_TTF_FALLBACK_UBUNTU_72
#define EOS_FONT_TTF_FALLBACK_PTR (lv_font_ubuntu_72)
#else
#define EOS_FONT_TTF_FALLBACK_PTR (&lv_font_montserrat_30)
#endif
#endif

#if EOS_FONT_TTF_ENABLE_EXTENDED
#ifndef EOS_FONT_TTF_KERNING
#define EOS_FONT_TTF_KERNING 0
#endif
#ifndef EOS_FONT_TTF_CACHE_SIZE
#define EOS_FONT_TTF_CACHE_SIZE 256
#endif
#endif

#endif /* EOS_FONT_TYPE */

/* Display ----------------------------------------------------*/

#ifndef EOS_DISPLAY_WIDTH
#define EOS_DISPLAY_WIDTH 390
#endif

#ifndef EOS_DISPLAY_HEIGHT
#define EOS_DISPLAY_HEIGHT 450
#endif

#ifndef EOS_DISPLAY_RADIUS
#define EOS_DISPLAY_RADIUS 80
#endif

#ifndef EOS_DISPLAY_BRIGHTNESS_MIN
#define EOS_DISPLAY_BRIGHTNESS_MIN 5
#endif

#ifndef EOS_DISPLAY_BRIGHTNESS_MAX
#define EOS_DISPLAY_BRIGHTNESS_MAX 100
#endif

/* File system ------------------------------------------------*/

#ifndef EOS_SYS_ROOT_DIR
#define EOS_SYS_ROOT_DIR "/"
#endif

#ifndef EOS_FS_TYPE
#define EOS_FS_TYPE EOS_FS_POSIX
#endif

#if EOS_FS_TYPE == EOS_FS_CUSTOM
#define EOS_FS_FILE_TYPE void *
#define EOS_FS_DIR_TYPE void *
#define EOS_FILE_INVALID NULL
#define EOS_DIR_INVALID NULL
#endif

#ifndef EOS_FS_PATH_MAX
#define EOS_FS_PATH_MAX 256
#endif

#ifndef EOS_LVGL_FS_LETTER
#define EOS_LVGL_FS_LETTER 'Z'
#endif

#ifndef EOS_DFW_ENABLE
#define EOS_DFW_ENABLE 0
#endif

/* Language ---------------------------------------------------*/

#ifndef EOS_CONFIG_DEFAULT_LANGUAGE
#define EOS_CONFIG_DEFAULT_LANGUAGE 0
#endif

/* Miscellaneous ----------------------------------------------*/

#ifndef EOS_ENABLE_TEST_APP
#define EOS_ENABLE_TEST_APP 1
#endif

/* Logging ----------------------------------------------------*/

#ifndef EOS_USE_ASSERT
#define EOS_USE_ASSERT 1
#endif

#ifndef EOS_ASSERT_HANDLER
#define EOS_ASSERT_HANDLER __builtin_trap();
#endif

#ifndef EOS_LOG_USE_COLOR
#define EOS_LOG_USE_COLOR 0
#endif

#ifndef EOS_LOG_MAX_LISTENERS
#define EOS_LOG_MAX_LISTENERS 8
#endif

#ifndef EOS_LOG_ENABLE_STD
#define EOS_LOG_ENABLE_STD 1
#endif

#endif /* EOS_CONFIG_DEFAULTS_H */
